plugins { id 'com.android.application' }

android {
    namespace 'ar.com.imaginar.ruletatermas'
    compileSdk 35

    defaultConfig {
        applicationId 'ar.com.imaginar.ruletatermas.webviewtest'
        minSdk 21
        targetSdk 25
        versionCode 110
        versionName 'webview-test-1.0'
    }

    buildTypes {
        debug { minifyEnabled false }
        release { minifyEnabled false; shrinkResources false }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
